export default [
  /* Files containing base styles that need to be overridden by more specific
   components should be listed first */
  'reset.css',
  'common-structural.css',
  'group.css',
  'popup.css',
  'grid-layout.css',
  'grid-borders.css',

  'advanced-filter.css',
  'borders-todo-move-into-component-files.css',
  'cell-editing.css',
  'charts.css',
  'column-drop.css',
  'column-select.css',
  'column-filters.css',
  'columns-tool-panel.css',
  'drag-and-drop.css',
  'header.css',
  'menu.css',
  'panel.css',
  'pinned-columns.css',
  'print.css',
  'select.css',
  'rich-select.css',
  'root.css',
  'sidebar.css',
  'button.css',
  'checkbox.css',
  'drag-handle.css',
  'inputs.css',
  'lists.css',
  'range.css',
  'toggle-button.css',
  'autocomplete.css',
  'tooltip.css',
  'chart-widgets-todo-split-into-separate-files.css',
  'filter-tool-panel.css',
  'paging-panel.css',
  'status-bar.css',
  'overlay.css',
  'icons.css',
  'icon-buttons.css',
];
